### ISSUE TITLE
How to make PRs for repos go to only some channels now?

### ISSUE THREAD

**Issue by stig** [binaryberry/seal#162]
We have a private fork because we don't want to confuse everyone with our config files. We've found it useful to have multiple slack channels / teams getting different list of PRs based on the repos in the config file.  Yesterday I upgraded to current master because I want to be able to send the different quotes to each team channel. Unfortunately this PR broke our seal.

I believe this commit is the culprit: https://github.com/binaryberry/seal/commit/12f37c67ac0c723ae6264d65f0851e0e7a22a722 (Yeah. It's a while since we upgraded...)  Now the seal moans about _every_ PR in every channel, ignoring each of our teams' repos list. Is there a way to get the seal to filter PRs to only the configured repos again? (Without reverting these changes, which I understand are good for other reasons.)

Is this something the `members` setting is meant to address? members is _much_ more fluid than repos for us: We rarely add repos, but members move around a lot. Therefore we specify `members: []` everywhere and would rather not change that.

If I have to add code to do this, would something like https://github.com/binaryberry/seal/pull/94 but for _including_ repos rather than excluding them be on the table?

**Comment by kentcb** [comment]
Arrived here looking for the same thing. In my case, different internal teams working on different projects only want to be notified about PRs in their repo (in separate slack channels). Whilst I can _exclude_ all repos apart from the relevant one on a per-team basis, that is obviously awful because every time a new repo is added I have to go and update all the configs to exclude it.

Shouldn't there be a whitelist approach rather than blacklist only? Something like this:
```
team:
  ...

  include_repos:
    - first
    - second
```
Only one of `exclude_repos` or `include_repos` would be allowed, not both.

**Comment by darkwinternight** [comment]
Agreed, `include_repos` would be nice to have!

**Comment by kentcb** [comment]
@darkwinternight I ended up doing this myself, but it's on a private copy of the repo (not a fork, since that needs to be public). I _might_ find the time to PR it at some point, but super busy rn.

**Comment by darkwinternight** [comment]
@kentcb If you don't find the time but you're willing to share your code, I can get it PR-ready.

**Comment by stig** [comment]
I think this issue can be deleted now that https://github.com/binaryberry/seal/pull/225 has been merged...? Can anybody confirm? (We no longer use seal, so I cannot myself. Sorry.)

**Comment by binaryberry** [comment]
Yes I believe so, thanks @stig !
