### ISSUE TITLE
Use GitHub search to power the seal

### ISSUE THREAD

**Issue by tijmenb** [binaryberry/seal#52]
I noticed our team is missing a few repos in the config, but instead of adding them I thought it would be nice to let the seal pick up new ones automatically.

Currently, the seal loops through all repos and fetches all pull requests. We could replace this with the issue search: https://developer.github.com/v3/search/#search-issues

```ruby
require 'octokit'
client = Octokit::Client.new
client.search_issues("is:pr is:open user:alphagov")
```

This will return all open PRs in all alphagov repos. It uses the same search syntax as github.com ([like this](https://github.com/search?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+user%3Aalphagov)).

This would mean 1) we can get rid of the `repos` in the configuration, 2) new repos are added automatically, 3) we save a bunch of requests.

Thoughts?

**Comment by binaryberry** [comment]
Thanks Tijmen! I had originally considered that approach but in the wrong way: I was getting a list of all alphagov repos (there are A LOT), then iterating over them to get open PRs, hence it was very slow (that's when I decided to add the list of repos, which I realised wasn't ideal).
Your way sounds like it might be much better as it's only one request, not one request to get the list of repos + one request per repo, which is a lot. I see at the minute there are [133](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Aalphagov) open PRs so that shouldn't be too long. Happy to take a pull request if you want to do it, and if not I'll make that improvement over the Christmas holidays. Thanks for the very good idea.
